/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef VOLCENGINE_CLB_MODIFYCERTIFICATEATTRIBUTESREQUEST_H
#define VOLCENGINE_CLB_MODIFYCERTIFICATEATTRIBUTESREQUEST_H
#include <string>
#include <volcengine/core/RequestBuilder.h>

namespace volcengine{
    namespace clb{
        class ModifyCertificateAttributesRequest {
        public:
            ModifyCertificateAttributesRequest();
            ~ModifyCertificateAttributesRequest() = default;

            RequestBuilder withRequestBuilder(RequestBuilder rb, const std::string &chain)const;

            const std::string &getCertificateId()const { return  v_certificateId; }
            bool CertificateIdHasBeenSet() const { return v_certificateIdHasBeenSet; }
            void setCertificateId(const std::string &s_certificateId ) {
                v_certificateId = s_certificateId;
                v_certificateIdHasBeenSet = true;
            }
            const std::string &getCertificateName()const { return  v_certificateName; }
            bool CertificateNameHasBeenSet() const { return v_certificateNameHasBeenSet; }
            void setCertificateName(const std::string &s_certificateName ) {
                v_certificateName = s_certificateName;
                v_certificateNameHasBeenSet = true;
            }
            const std::string &getDescription()const { return  v_description; }
            bool DescriptionHasBeenSet() const { return v_descriptionHasBeenSet; }
            void setDescription(const std::string &s_description ) {
                v_description = s_description;
                v_descriptionHasBeenSet = true;
            }
        private:
            std::string v_certificateId;
            bool v_certificateIdHasBeenSet;

            std::string v_certificateName;
            bool v_certificateNameHasBeenSet;

            std::string v_description;
            bool v_descriptionHasBeenSet;

        };
    }
}
#endif // !VOLCENGINE_CLB_MODIFYCERTIFICATEATTRIBUTESREQUEST_H