/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef VOLCENGINE_CLB_RESULTFORDESCRIBELISTENERHEALTHOUTPUT_H
#define VOLCENGINE_CLB_RESULTFORDESCRIBELISTENERHEALTHOUTPUT_H
#include <string>
#include <volcengine/core/RequestBuilder.h>
#include "volcengine/core/utils/json.hpp"
namespace volcengine{
    namespace clb{
        class ResultForDescribeListenerHealthOutput {
        public:
            ResultForDescribeListenerHealthOutput() = default;
            ~ResultForDescribeListenerHealthOutput() = default;
            void fromJsonString(const std::string &input);
            const std::string &getInstanceId() const { return  v_instanceId; }
            void setInstanceId(const std::string &s_instanceId ) {
                v_instanceId = s_instanceId;
            }
            const std::string &getIp() const { return  v_ip; }
            void setIp(const std::string &s_ip ) {
                v_ip = s_ip;
            }
            const int getPort() const { return  v_port; }
            void setPort(const int s_port ) {
                v_port = s_port;
            }
            const int getRuleNumber() const { return  v_ruleNumber; }
            void setRuleNumber(const int s_ruleNumber ) {
                v_ruleNumber = s_ruleNumber;
            }
            const std::string &getServerGroupId() const { return  v_serverGroupId; }
            void setServerGroupId(const std::string &s_serverGroupId ) {
                v_serverGroupId = s_serverGroupId;
            }
            const std::string &getServerId() const { return  v_serverId; }
            void setServerId(const std::string &s_serverId ) {
                v_serverId = s_serverId;
            }
            const std::string &getStatus() const { return  v_status; }
            void setStatus(const std::string &s_status ) {
                v_status = s_status;
            }
            const std::string &getType() const { return  v_type; }
            void setType(const std::string &s_type ) {
                v_type = s_type;
            }
        private:
            std::string v_instanceId;
            std::string v_ip;
            int v_port{};
            int v_ruleNumber{};
            std::string v_serverGroupId;
            std::string v_serverId;
            std::string v_status;
            std::string v_type;
        };
    }
}
#endif // !VOLCENGINE_CLB_RESULTFORDESCRIBELISTENERHEALTHOUTPUT_H