/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef VOLCENGINE_CLB_SERVERGROUPFORDESCRIBESERVERGROUPSOUTPUT_H
#define VOLCENGINE_CLB_SERVERGROUPFORDESCRIBESERVERGROUPSOUTPUT_H
#include <string>
#include <volcengine/core/RequestBuilder.h>
#include "volcengine/core/utils/json.hpp"
namespace volcengine{
    namespace clb{
        class ServerGroupForDescribeServerGroupsOutput {
        public:
            ServerGroupForDescribeServerGroupsOutput() = default;
            ~ServerGroupForDescribeServerGroupsOutput() = default;
            void fromJsonString(const std::string &input);
            const std::string &getCreateTime() const { return  v_createTime; }
            void setCreateTime(const std::string &s_createTime ) {
                v_createTime = s_createTime;
            }
            const std::string &getDescription() const { return  v_description; }
            void setDescription(const std::string &s_description ) {
                v_description = s_description;
            }
            const std::string &getServerGroupId() const { return  v_serverGroupId; }
            void setServerGroupId(const std::string &s_serverGroupId ) {
                v_serverGroupId = s_serverGroupId;
            }
            const std::string &getServerGroupName() const { return  v_serverGroupName; }
            void setServerGroupName(const std::string &s_serverGroupName ) {
                v_serverGroupName = s_serverGroupName;
            }
            const std::string &getUpdateTime() const { return  v_updateTime; }
            void setUpdateTime(const std::string &s_updateTime ) {
                v_updateTime = s_updateTime;
            }
        private:
            std::string v_createTime;
            std::string v_description;
            std::string v_serverGroupId;
            std::string v_serverGroupName;
            std::string v_updateTime;
        };
    }
}
#endif // !VOLCENGINE_CLB_SERVERGROUPFORDESCRIBESERVERGROUPSOUTPUT_H