/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef VOLCENGINE_VKE_CREATEDEFAULTNODEPOOLREQUEST_H
#define VOLCENGINE_VKE_CREATEDEFAULTNODEPOOLREQUEST_H
#include <string>
#include "volcengine/core/utils/json.hpp"
#include <volcengine/core/RequestBuilder.h>
#include "volcengine/vke/model/KubernetesConfigForCreateDefaultNodePoolInput.h"
#include "volcengine/vke/model/NodeConfigForCreateDefaultNodePoolInput.h"
#include "volcengine/vke/model/TagForCreateDefaultNodePoolInput.h"
using namespace nlohmann;

namespace volcengine{
    namespace vke{
        class CreateDefaultNodePoolRequest {
        public:
            CreateDefaultNodePoolRequest();
            ~CreateDefaultNodePoolRequest() = default;

            static RequestBuilder withRequestBuilder(RequestBuilder rb, const std::string &chain);
            json jsonPayload() const;

            const std::string &getClientToken()const { return  v_clientToken; }
            bool ClientTokenHasBeenSet() const { return v_clientTokenHasBeenSet; }
            void setClientToken(const std::string &s_clientToken ) {
                v_clientToken = s_clientToken;
                v_clientTokenHasBeenSet = true;
            }
            const std::string &getClusterId()const { return  v_clusterId; }
            bool ClusterIdHasBeenSet() const { return v_clusterIdHasBeenSet; }
            void setClusterId(const std::string &s_clusterId ) {
                v_clusterId = s_clusterId;
                v_clusterIdHasBeenSet = true;
            }
            const std::shared_ptr<KubernetesConfigForCreateDefaultNodePoolInput> &getKubernetesConfig()const { return  v_kubernetesConfig; }
            bool KubernetesConfigHasBeenSet() const { return v_kubernetesConfigHasBeenSet; }
            void setKubernetesConfig(const std::shared_ptr<KubernetesConfigForCreateDefaultNodePoolInput> &s_kubernetesConfig ) {
                v_kubernetesConfig = s_kubernetesConfig;
                v_kubernetesConfigHasBeenSet = true;
            }
            const std::shared_ptr<NodeConfigForCreateDefaultNodePoolInput> &getNodeConfig()const { return  v_nodeConfig; }
            bool NodeConfigHasBeenSet() const { return v_nodeConfigHasBeenSet; }
            void setNodeConfig(const std::shared_ptr<NodeConfigForCreateDefaultNodePoolInput> &s_nodeConfig ) {
                v_nodeConfig = s_nodeConfig;
                v_nodeConfigHasBeenSet = true;
            }
            const std::vector<TagForCreateDefaultNodePoolInput> &getTags()const { return  v_tags; }
            bool TagsHasBeenSet() const { return v_tagsHasBeenSet; }
            void setTags(const std::vector<TagForCreateDefaultNodePoolInput> &s_tags ) {
                v_tags = s_tags;
                v_tagsHasBeenSet = true;
            }
        private:
            std::string v_clientToken;
            bool v_clientTokenHasBeenSet;

            std::string v_clusterId;
            bool v_clusterIdHasBeenSet;

            std::shared_ptr<KubernetesConfigForCreateDefaultNodePoolInput> v_kubernetesConfig;
            bool v_kubernetesConfigHasBeenSet;

            std::shared_ptr<NodeConfigForCreateDefaultNodePoolInput> v_nodeConfig;
            bool v_nodeConfigHasBeenSet;

            std::vector<TagForCreateDefaultNodePoolInput> v_tags;
            bool v_tagsHasBeenSet;

        };
    }
}
#endif // !VOLCENGINE_VKE_CREATEDEFAULTNODEPOOLREQUEST_H