/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef VOLCENGINE_VKE_LOGGINGCONFIGFORLISTCLUSTERSOUTPUT_H
#define VOLCENGINE_VKE_LOGGINGCONFIGFORLISTCLUSTERSOUTPUT_H
#include <string>
#include <volcengine/core/RequestBuilder.h>
#include "volcengine/core/utils/json.hpp"
#include "volcengine/vke/model/LogSetupForListClustersOutput.h"
namespace volcengine{
    namespace vke{
        class LoggingConfigForListClustersOutput {
        public:
            LoggingConfigForListClustersOutput() = default;
            ~LoggingConfigForListClustersOutput() = default;
            void fromJsonString(const std::string &input);
            const std::string &getLogProjectId() const { return  v_logProjectId; }
            void setLogProjectId(const std::string &s_logProjectId ) {
                v_logProjectId = s_logProjectId;
            }
            const std::vector<LogSetupForListClustersOutput> &getLogSetups() const { return  v_logSetups; }
            void setLogSetups(const std::vector<LogSetupForListClustersOutput> &s_logSetups ) {
                v_logSetups = s_logSetups;
            }
        private:
            std::string v_logProjectId;
            std::vector<LogSetupForListClustersOutput> v_logSetups;
        };
    }
}
#endif // !VOLCENGINE_VKE_LOGGINGCONFIGFORLISTCLUSTERSOUTPUT_H