/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef VOLCENGINE_VKE_STATUSFORLISTNODEPOOLSINPUT_H
#define VOLCENGINE_VKE_STATUSFORLISTNODEPOOLSINPUT_H
#include <string>
#include "volcengine/core/utils/json.hpp"
#include <volcengine/core/RequestBuilder.h>
using namespace nlohmann;

namespace volcengine{
    namespace vke{
        class StatusForListNodePoolsInput {
        public:
            StatusForListNodePoolsInput();
            ~StatusForListNodePoolsInput() = default;

            static RequestBuilder withRequestBuilder(RequestBuilder rb, const std::string &chain);
            json jsonPayload() const;

            const std::string &getConditionsType()const { return  v_conditionsType; }
            bool ConditionsTypeHasBeenSet() const { return v_conditionsTypeHasBeenSet; }
            void setConditionsType(const std::string &s_conditionsType ) {
                v_conditionsType = s_conditionsType;
                v_conditionsTypeHasBeenSet = true;
            }
            const std::string &getPhase()const { return  v_phase; }
            bool PhaseHasBeenSet() const { return v_phaseHasBeenSet; }
            void setPhase(const std::string &s_phase ) {
                v_phase = s_phase;
                v_phaseHasBeenSet = true;
            }
        private:
            std::string v_conditionsType;
            bool v_conditionsTypeHasBeenSet;

            std::string v_phase;
            bool v_phaseHasBeenSet;

        };
    }
}
#endif // !VOLCENGINE_VKE_STATUSFORLISTNODEPOOLSINPUT_H