/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef VOLCENGINE_VKE_VERSIONFORLISTSUPPORTEDADDONSOUTPUT_H
#define VOLCENGINE_VKE_VERSIONFORLISTSUPPORTEDADDONSOUTPUT_H
#include <string>
#include <volcengine/core/RequestBuilder.h>
#include "volcengine/core/utils/json.hpp"
#include "volcengine/vke/model/CompatibilityForListSupportedAddonsOutput.h"
namespace volcengine{
    namespace vke{
        class VersionForListSupportedAddonsOutput {
        public:
            VersionForListSupportedAddonsOutput() = default;
            ~VersionForListSupportedAddonsOutput() = default;
            void fromJsonString(const std::string &input);
            const std::vector<CompatibilityForListSupportedAddonsOutput> &getCompatibilities() const { return  v_compatibilities; }
            void setCompatibilities(const std::vector<CompatibilityForListSupportedAddonsOutput> &s_compatibilities ) {
                v_compatibilities = s_compatibilities;
            }
            const std::vector<std::string> &getCompatibleVersions() const { return  v_compatibleVersions; }
            void setCompatibleVersions(const std::vector<std::string> &s_compatibleVersions ) {
                v_compatibleVersions = s_compatibleVersions;
            }
            const std::string &getVersion() const { return  v_version; }
            void setVersion(const std::string &s_version ) {
                v_version = s_version;
            }
        private:
            std::vector<CompatibilityForListSupportedAddonsOutput> v_compatibilities;
            std::vector<std::string> v_compatibleVersions;
            std::string v_version;
        };
    }
}
#endif // !VOLCENGINE_VKE_VERSIONFORLISTSUPPORTEDADDONSOUTPUT_H