/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#include "volcengine/vpc/model/BandwidthPackageForDescribeBandwidthPackagesOutput.h"

using namespace volcengine;
using namespace volcengine::vpc;
using namespace nlohmann;

void BandwidthPackageForDescribeBandwidthPackagesOutput::fromJsonString(const std::string &input) {
    auto j = json::parse(input);
    if (j.contains("Bandwidth")) j.at("Bandwidth").get_to(v_bandwidth);
    if (j.contains("BandwidthPackageId")) j.at("BandwidthPackageId").get_to(v_bandwidthPackageId);
    if (j.contains("BandwidthPackageName")) j.at("BandwidthPackageName").get_to(v_bandwidthPackageName);
    if (j.contains("BillingType")) j.at("BillingType").get_to(v_billingType);
    if (j.contains("BusinessStatus")) j.at("BusinessStatus").get_to(v_businessStatus);
    if (j.contains("CreationTime")) j.at("CreationTime").get_to(v_creationTime);
    if (j.contains("DeletedTime")) j.at("DeletedTime").get_to(v_deletedTime);
    if (j.contains("Description")) j.at("Description").get_to(v_description);
    if (j.contains("EipAddresses")){
        json eipAddressesPres = j.at("EipAddresses");
        for (auto & pre : eipAddressesPres) {
           EipAddressForDescribeBandwidthPackagesOutput next;
           next.fromJsonString(to_string(pre));
           v_eipAddresses.emplace_back(next);
        }
    }
    if (j.contains("ISP")) j.at("ISP").get_to(v_iSP);
    if (j.contains("OverdueTime")) j.at("OverdueTime").get_to(v_overdueTime);
    if (j.contains("ProjectName")) j.at("ProjectName").get_to(v_projectName);
    if (j.contains("SecurityProtectionTypes")){
        json securityProtectionTypesPres = j.at("SecurityProtectionTypes");
        for (auto & pre : securityProtectionTypesPres) {
           v_securityProtectionTypes.emplace_back(pre);
        }
    }
    if (j.contains("Status")) j.at("Status").get_to(v_status);
    if (j.contains("Tags")){
        json tagsPres = j.at("Tags");
        for (auto & pre : tagsPres) {
           TagForDescribeBandwidthPackagesOutput next;
           next.fromJsonString(to_string(pre));
           v_tags.emplace_back(next);
        }
    }
    if (j.contains("UpdateTime")) j.at("UpdateTime").get_to(v_updateTime);
}
