/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#include <sstream>
#include <volcengine/core/RequestBuilder.h>
#include <volcengine/core/utils/StringUtils.h>
#include "volcengine/vpc/model/CreateRouteEntryRequest.h"

using namespace volcengine;
using namespace volcengine::vpc;
CreateRouteEntryRequest::CreateRouteEntryRequest() = default;

RequestBuilder CreateRouteEntryRequest::withRequestBuilder(RequestBuilder rb, const std::string &chain) const {
    rb.withQuery("Action","CreateRouteEntry");
    rb.withQuery("Version","2020-04-01");

    if(v_clientTokenHasBeenSet){
        rb.withQuery(chain + "ClientToken", v_clientToken);

    }

    if(v_descriptionHasBeenSet){
        rb.withQuery(chain + "Description", v_description);

    }

    if(v_destinationCidrBlockHasBeenSet){
        rb.withQuery(chain + "DestinationCidrBlock", v_destinationCidrBlock);

    }

    if(v_nextHopIdHasBeenSet){
        rb.withQuery(chain + "NextHopId", v_nextHopId);

    }

    if(v_nextHopTypeHasBeenSet){
        rb.withQuery(chain + "NextHopType", v_nextHopType);

    }

    if(v_routeEntryNameHasBeenSet){
        rb.withQuery(chain + "RouteEntryName", v_routeEntryName);

    }

    if(v_routeTableIdHasBeenSet){
        rb.withQuery(chain + "RouteTableId", v_routeTableId);

    }

    return rb;
}


