/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#include <sstream>
#include <volcengine/core/RequestBuilder.h>
#include <volcengine/core/utils/StringUtils.h>
#include "volcengine/vpc/model/DescribeEipAddressesRequest.h"

using namespace volcengine;
using namespace volcengine::vpc;
DescribeEipAddressesRequest::DescribeEipAddressesRequest(){
    v_billingType = 0;
    v_billingTypeHasBeenSet = false;
    v_pageNumber = 0;
    v_pageNumberHasBeenSet = false;
    v_pageSize = 0;
    v_pageSizeHasBeenSet = false;
    v_securityProtectionEnabled = false;
    v_securityProtectionEnabledHasBeenSet = false;
}

RequestBuilder DescribeEipAddressesRequest::withRequestBuilder(RequestBuilder rb, const std::string &chain) const {
    rb.withQuery("Action","DescribeEipAddresses");
    rb.withQuery("Version","2020-04-01");

    if(v_allocationIdsHasBeenSet){
      unsigned v_allocationIdsCount = 1;
      for(auto& item : v_allocationIds){
        std::stringstream ss;
        ss << chain << "AllocationIds." << v_allocationIdsCount;
        rb.withQuery(ss.str(), item);
        v_allocationIdsCount ++;
      }
    }

    if(v_associatedInstanceIdHasBeenSet){
        rb.withQuery(chain + "AssociatedInstanceId", v_associatedInstanceId);

    }

    if(v_associatedInstanceTypeHasBeenSet){
        rb.withQuery(chain + "AssociatedInstanceType", v_associatedInstanceType);

    }

    if(v_billingTypeHasBeenSet){
        rb.withQuery(chain + "BillingType", std::to_string(v_billingType));

    }

    if(v_eipAddressesHasBeenSet){
      unsigned v_eipAddressesCount = 1;
      for(auto& item : v_eipAddresses){
        std::stringstream ss;
        ss << chain << "EipAddresses." << v_eipAddressesCount;
        rb.withQuery(ss.str(), item);
        v_eipAddressesCount ++;
      }
    }

    if(v_iSPHasBeenSet){
        rb.withQuery(chain + "ISP", v_iSP);

    }

    if(v_nameHasBeenSet){
        rb.withQuery(chain + "Name", v_name);

    }

    if(v_pageNumberHasBeenSet){
        rb.withQuery(chain + "PageNumber", std::to_string(v_pageNumber));

    }

    if(v_pageSizeHasBeenSet){
        rb.withQuery(chain + "PageSize", std::to_string(v_pageSize));

    }

    if(v_projectNameHasBeenSet){
        rb.withQuery(chain + "ProjectName", v_projectName);

    }

    if(v_securityProtectionEnabledHasBeenSet){
        rb.withQuery(chain + "SecurityProtectionEnabled", std::to_string(v_securityProtectionEnabled));

    }

    if(v_statusHasBeenSet){
        rb.withQuery(chain + "Status", v_status);

    }

    if(v_tagFiltersHasBeenSet){
      unsigned v_tagFiltersCount = 1;
      for(auto& item : v_tagFilters){
        std::stringstream ss;
        ss << chain << "TagFilters." << v_tagFiltersCount;
        rb = item.withRequestBuilder(rb, ss.str()+".");
        v_tagFiltersCount ++;
      }
    }

    return rb;
}


