/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#include "volcengine/vpc/model/PermissionForDescribeSecurityGroupAttributesOutput.h"

using namespace volcengine;
using namespace volcengine::vpc;
using namespace nlohmann;

void PermissionForDescribeSecurityGroupAttributesOutput::fromJsonString(const std::string &input) {
    auto j = json::parse(input);
    if (j.contains("CidrIp")) j.at("CidrIp").get_to(v_cidrIp);
    if (j.contains("CreationTime")) j.at("CreationTime").get_to(v_creationTime);
    if (j.contains("Description")) j.at("Description").get_to(v_description);
    if (j.contains("Direction")) j.at("Direction").get_to(v_direction);
    if (j.contains("Policy")) j.at("Policy").get_to(v_policy);
    if (j.contains("PortEnd")) j.at("PortEnd").get_to(v_portEnd);
    if (j.contains("PortStart")) j.at("PortStart").get_to(v_portStart);
    if (j.contains("Priority")) j.at("Priority").get_to(v_priority);
    if (j.contains("Protocol")) j.at("Protocol").get_to(v_protocol);
    if (j.contains("SourceGroupId")) j.at("SourceGroupId").get_to(v_sourceGroupId);
    if (j.contains("UpdateTime")) j.at("UpdateTime").get_to(v_updateTime);
}
