/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef VOLCENGINE_DIRECTCONNECT_MODIFYBGPPEERATTRIBUTESREQUEST_H
#define VOLCENGINE_DIRECTCONNECT_MODIFYBGPPEERATTRIBUTESREQUEST_H
#include <string>
#include <volcengine/core/RequestBuilder.h>

namespace volcengine{
    namespace directconnect{
        class ModifyBgpPeerAttributesRequest {
        public:
            ModifyBgpPeerAttributesRequest();
            ~ModifyBgpPeerAttributesRequest() = default;

            RequestBuilder withRequestBuilder(RequestBuilder rb, const std::string &chain)const;

            const std::string &getBgpPeerId()const { return  v_bgpPeerId; }
            bool BgpPeerIdHasBeenSet() const { return v_bgpPeerIdHasBeenSet; }
            void setBgpPeerId(const std::string &s_bgpPeerId ) {
                v_bgpPeerId = s_bgpPeerId;
                v_bgpPeerIdHasBeenSet = true;
            }
            const std::string &getBgpPeerName()const { return  v_bgpPeerName; }
            bool BgpPeerNameHasBeenSet() const { return v_bgpPeerNameHasBeenSet; }
            void setBgpPeerName(const std::string &s_bgpPeerName ) {
                v_bgpPeerName = s_bgpPeerName;
                v_bgpPeerNameHasBeenSet = true;
            }
            const std::string &getDescription()const { return  v_description; }
            bool DescriptionHasBeenSet() const { return v_descriptionHasBeenSet; }
            void setDescription(const std::string &s_description ) {
                v_description = s_description;
                v_descriptionHasBeenSet = true;
            }
        private:
            std::string v_bgpPeerId;
            bool v_bgpPeerIdHasBeenSet;

            std::string v_bgpPeerName;
            bool v_bgpPeerNameHasBeenSet;

            std::string v_description;
            bool v_descriptionHasBeenSet;

        };
    }
}
#endif // !VOLCENGINE_DIRECTCONNECT_MODIFYBGPPEERATTRIBUTESREQUEST_H