/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#include "volcengine/vke/model/AutoScalingForListNodePoolsOutput.h"

using namespace volcengine;
using namespace volcengine::vke;
using namespace nlohmann;

void AutoScalingForListNodePoolsOutput::fromJsonString(const std::string &input) {
    auto j = json::parse(input);
    if (j.contains("DesiredReplicas")) j.at("DesiredReplicas").get_to(v_desiredReplicas);
    if (j.contains("Enabled")) j.at("Enabled").get_to(v_enabled);
    if (j.contains("MaxReplicas")) j.at("MaxReplicas").get_to(v_maxReplicas);
    if (j.contains("MinReplicas")) j.at("MinReplicas").get_to(v_minReplicas);
    if (j.contains("Priority")) j.at("Priority").get_to(v_priority);
    if (j.contains("SubnetPolicy")) j.at("SubnetPolicy").get_to(v_subnetPolicy);
}
