/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef VOLCENGINE_DIRECTCONNECT_DIRECTCONNECTCLIENT_H
#define VOLCENGINE_DIRECTCONNECT_DIRECTCONNECTCLIENT_H
#include <string>
#include <volcengine/core/ResultData.h>
#include <volcengine/core/VolcengineMetaData.h>
#include <volcengine/core/VolcengineClient.h>
#include "volcengine/directconnect/model/CreateBgpPeerRequest.h"
#include "volcengine/directconnect/model/CreateBgpPeerResult.h"
#include "volcengine/directconnect/model/CreateDirectConnectConnectionRequest.h"
#include "volcengine/directconnect/model/CreateDirectConnectConnectionResult.h"
#include "volcengine/directconnect/model/CreateDirectConnectConnectionOrderRequest.h"
#include "volcengine/directconnect/model/CreateDirectConnectConnectionOrderResult.h"
#include "volcengine/directconnect/model/CreateDirectConnectGatewayRequest.h"
#include "volcengine/directconnect/model/CreateDirectConnectGatewayResult.h"
#include "volcengine/directconnect/model/CreateDirectConnectGatewayRouteRequest.h"
#include "volcengine/directconnect/model/CreateDirectConnectGatewayRouteResult.h"
#include "volcengine/directconnect/model/CreateDirectConnectVirtualInterfaceRequest.h"
#include "volcengine/directconnect/model/CreateDirectConnectVirtualInterfaceResult.h"
#include "volcengine/directconnect/model/DeleteBgpPeerRequest.h"
#include "volcengine/directconnect/model/DeleteBgpPeerResult.h"
#include "volcengine/directconnect/model/DeleteDirectConnectConnectionRequest.h"
#include "volcengine/directconnect/model/DeleteDirectConnectConnectionResult.h"
#include "volcengine/directconnect/model/DeleteDirectConnectGatewayRequest.h"
#include "volcengine/directconnect/model/DeleteDirectConnectGatewayResult.h"
#include "volcengine/directconnect/model/DeleteDirectConnectGatewayRouteRequest.h"
#include "volcengine/directconnect/model/DeleteDirectConnectGatewayRouteResult.h"
#include "volcengine/directconnect/model/DeleteDirectConnectVirtualInterfaceRequest.h"
#include "volcengine/directconnect/model/DeleteDirectConnectVirtualInterfaceResult.h"
#include "volcengine/directconnect/model/DescribeBgpPeerAttributesRequest.h"
#include "volcengine/directconnect/model/DescribeBgpPeerAttributesResult.h"
#include "volcengine/directconnect/model/DescribeBgpPeersRequest.h"
#include "volcengine/directconnect/model/DescribeBgpPeersResult.h"
#include "volcengine/directconnect/model/DescribeDirectConnectAccessPointsRequest.h"
#include "volcengine/directconnect/model/DescribeDirectConnectAccessPointsResult.h"
#include "volcengine/directconnect/model/DescribeDirectConnectConnectionAttributesRequest.h"
#include "volcengine/directconnect/model/DescribeDirectConnectConnectionAttributesResult.h"
#include "volcengine/directconnect/model/DescribeDirectConnectConnectionsRequest.h"
#include "volcengine/directconnect/model/DescribeDirectConnectConnectionsResult.h"
#include "volcengine/directconnect/model/DescribeDirectConnectGatewayAttributesRequest.h"
#include "volcengine/directconnect/model/DescribeDirectConnectGatewayAttributesResult.h"
#include "volcengine/directconnect/model/DescribeDirectConnectGatewayRouteAttributesRequest.h"
#include "volcengine/directconnect/model/DescribeDirectConnectGatewayRouteAttributesResult.h"
#include "volcengine/directconnect/model/DescribeDirectConnectGatewayRoutesRequest.h"
#include "volcengine/directconnect/model/DescribeDirectConnectGatewayRoutesResult.h"
#include "volcengine/directconnect/model/DescribeDirectConnectGatewaysRequest.h"
#include "volcengine/directconnect/model/DescribeDirectConnectGatewaysResult.h"
#include "volcengine/directconnect/model/DescribeDirectConnectVirtualInterfaceAttributesRequest.h"
#include "volcengine/directconnect/model/DescribeDirectConnectVirtualInterfaceAttributesResult.h"
#include "volcengine/directconnect/model/DescribeDirectConnectVirtualInterfacesRequest.h"
#include "volcengine/directconnect/model/DescribeDirectConnectVirtualInterfacesResult.h"
#include "volcengine/directconnect/model/ModifyBgpPeerAttributesRequest.h"
#include "volcengine/directconnect/model/ModifyBgpPeerAttributesResult.h"
#include "volcengine/directconnect/model/ModifyDirectConnectConnectionAttributesRequest.h"
#include "volcengine/directconnect/model/ModifyDirectConnectConnectionAttributesResult.h"
#include "volcengine/directconnect/model/ModifyDirectConnectGatewayAttributesRequest.h"
#include "volcengine/directconnect/model/ModifyDirectConnectGatewayAttributesResult.h"
#include "volcengine/directconnect/model/ModifyDirectConnectVirtualInterfaceAttributesRequest.h"
#include "volcengine/directconnect/model/ModifyDirectConnectVirtualInterfaceAttributesResult.h"
namespace volcengine{
    namespace directconnect{
        class DirectconnectClient {
        public:
            explicit DirectconnectClient(const std::shared_ptr<VolcengineClientConfig> &config);

            ~DirectconnectClient() = default;

            ResultData<VolcengineMetadata, CreateBgpPeerResult> CreateBgpPeer(const CreateBgpPeerRequest &input) const;

            ResultData<VolcengineMetadata, CreateDirectConnectConnectionResult> CreateDirectConnectConnection(const CreateDirectConnectConnectionRequest &input) const;

            ResultData<VolcengineMetadata, CreateDirectConnectConnectionOrderResult> CreateDirectConnectConnectionOrder(const CreateDirectConnectConnectionOrderRequest &input) const;

            ResultData<VolcengineMetadata, CreateDirectConnectGatewayResult> CreateDirectConnectGateway(const CreateDirectConnectGatewayRequest &input) const;

            ResultData<VolcengineMetadata, CreateDirectConnectGatewayRouteResult> CreateDirectConnectGatewayRoute(const CreateDirectConnectGatewayRouteRequest &input) const;

            ResultData<VolcengineMetadata, CreateDirectConnectVirtualInterfaceResult> CreateDirectConnectVirtualInterface(const CreateDirectConnectVirtualInterfaceRequest &input) const;

            ResultData<VolcengineMetadata, DeleteBgpPeerResult> DeleteBgpPeer(const DeleteBgpPeerRequest &input) const;

            ResultData<VolcengineMetadata, DeleteDirectConnectConnectionResult> DeleteDirectConnectConnection(const DeleteDirectConnectConnectionRequest &input) const;

            ResultData<VolcengineMetadata, DeleteDirectConnectGatewayResult> DeleteDirectConnectGateway(const DeleteDirectConnectGatewayRequest &input) const;

            ResultData<VolcengineMetadata, DeleteDirectConnectGatewayRouteResult> DeleteDirectConnectGatewayRoute(const DeleteDirectConnectGatewayRouteRequest &input) const;

            ResultData<VolcengineMetadata, DeleteDirectConnectVirtualInterfaceResult> DeleteDirectConnectVirtualInterface(const DeleteDirectConnectVirtualInterfaceRequest &input) const;

            ResultData<VolcengineMetadata, DescribeBgpPeerAttributesResult> DescribeBgpPeerAttributes(const DescribeBgpPeerAttributesRequest &input) const;

            ResultData<VolcengineMetadata, DescribeBgpPeersResult> DescribeBgpPeers(const DescribeBgpPeersRequest &input) const;

            ResultData<VolcengineMetadata, DescribeDirectConnectAccessPointsResult> DescribeDirectConnectAccessPoints(const DescribeDirectConnectAccessPointsRequest &input) const;

            ResultData<VolcengineMetadata, DescribeDirectConnectConnectionAttributesResult> DescribeDirectConnectConnectionAttributes(const DescribeDirectConnectConnectionAttributesRequest &input) const;

            ResultData<VolcengineMetadata, DescribeDirectConnectConnectionsResult> DescribeDirectConnectConnections(const DescribeDirectConnectConnectionsRequest &input) const;

            ResultData<VolcengineMetadata, DescribeDirectConnectGatewayAttributesResult> DescribeDirectConnectGatewayAttributes(const DescribeDirectConnectGatewayAttributesRequest &input) const;

            ResultData<VolcengineMetadata, DescribeDirectConnectGatewayRouteAttributesResult> DescribeDirectConnectGatewayRouteAttributes(const DescribeDirectConnectGatewayRouteAttributesRequest &input) const;

            ResultData<VolcengineMetadata, DescribeDirectConnectGatewayRoutesResult> DescribeDirectConnectGatewayRoutes(const DescribeDirectConnectGatewayRoutesRequest &input) const;

            ResultData<VolcengineMetadata, DescribeDirectConnectGatewaysResult> DescribeDirectConnectGateways(const DescribeDirectConnectGatewaysRequest &input) const;

            ResultData<VolcengineMetadata, DescribeDirectConnectVirtualInterfaceAttributesResult> DescribeDirectConnectVirtualInterfaceAttributes(const DescribeDirectConnectVirtualInterfaceAttributesRequest &input) const;

            ResultData<VolcengineMetadata, DescribeDirectConnectVirtualInterfacesResult> DescribeDirectConnectVirtualInterfaces(const DescribeDirectConnectVirtualInterfacesRequest &input) const;

            ResultData<VolcengineMetadata, ModifyBgpPeerAttributesResult> ModifyBgpPeerAttributes(const ModifyBgpPeerAttributesRequest &input) const;

            ResultData<VolcengineMetadata, ModifyDirectConnectConnectionAttributesResult> ModifyDirectConnectConnectionAttributes(const ModifyDirectConnectConnectionAttributesRequest &input) const;

            ResultData<VolcengineMetadata, ModifyDirectConnectGatewayAttributesResult> ModifyDirectConnectGatewayAttributes(const ModifyDirectConnectGatewayAttributesRequest &input) const;

            ResultData<VolcengineMetadata, ModifyDirectConnectVirtualInterfaceAttributesResult> ModifyDirectConnectVirtualInterfaceAttributes(const ModifyDirectConnectVirtualInterfaceAttributesRequest &input) const;

        private:
            std::shared_ptr<VolcengineClient> client_;
            std::string svc_ = "directconnect";
        };
    }
}
#endif // !VOLCENGINE_DIRECTCONNECT_DIRECTCONNECTCLIENT_H