/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef VOLCENGINE_ECS_AVAILABLEZONEFORDESCRIBEAVAILABLERESOURCEOUTPUT_H
#define VOLCENGINE_ECS_AVAILABLEZONEFORDESCRIBEAVAILABLERESOURCEOUTPUT_H
#include <string>
#include <volcengine/core/RequestBuilder.h>
#include "volcengine/core/utils/json.hpp"
#include "volcengine/ecs/model/AvailableResourceForDescribeAvailableResourceOutput.h"
namespace volcengine{
    namespace ecs{
        class AvailableZoneForDescribeAvailableResourceOutput {
        public:
            AvailableZoneForDescribeAvailableResourceOutput() = default;
            ~AvailableZoneForDescribeAvailableResourceOutput() = default;
            void fromJsonString(const std::string &input);
            const std::vector<AvailableResourceForDescribeAvailableResourceOutput> &getAvailableResources() const { return  v_availableResources; }
            void setAvailableResources(const std::vector<AvailableResourceForDescribeAvailableResourceOutput> &s_availableResources ) {
                v_availableResources = s_availableResources;
            }
            const std::string &getRegionId() const { return  v_regionId; }
            void setRegionId(const std::string &s_regionId ) {
                v_regionId = s_regionId;
            }
            const std::string &getStatus() const { return  v_status; }
            void setStatus(const std::string &s_status ) {
                v_status = s_status;
            }
            const std::string &getZoneId() const { return  v_zoneId; }
            void setZoneId(const std::string &s_zoneId ) {
                v_zoneId = s_zoneId;
            }
        private:
            std::vector<AvailableResourceForDescribeAvailableResourceOutput> v_availableResources;
            std::string v_regionId;
            std::string v_status;
            std::string v_zoneId;
        };
    }
}
#endif // !VOLCENGINE_ECS_AVAILABLEZONEFORDESCRIBEAVAILABLERESOURCEOUTPUT_H