/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef VOLCENGINE_ECS_CREATEDEPLOYMENTSETREQUEST_H
#define VOLCENGINE_ECS_CREATEDEPLOYMENTSETREQUEST_H
#include <string>
#include <volcengine/core/RequestBuilder.h>

namespace volcengine{
    namespace ecs{
        class CreateDeploymentSetRequest {
        public:
            CreateDeploymentSetRequest();
            ~CreateDeploymentSetRequest() = default;

            RequestBuilder withRequestBuilder(RequestBuilder rb, const std::string &chain)const;

            const std::string &getClientToken()const { return  v_clientToken; }
            bool ClientTokenHasBeenSet() const { return v_clientTokenHasBeenSet; }
            void setClientToken(const std::string &s_clientToken ) {
                v_clientToken = s_clientToken;
                v_clientTokenHasBeenSet = true;
            }
            const std::string &getDeploymentSetName()const { return  v_deploymentSetName; }
            bool DeploymentSetNameHasBeenSet() const { return v_deploymentSetNameHasBeenSet; }
            void setDeploymentSetName(const std::string &s_deploymentSetName ) {
                v_deploymentSetName = s_deploymentSetName;
                v_deploymentSetNameHasBeenSet = true;
            }
            const std::string &getDescription()const { return  v_description; }
            bool DescriptionHasBeenSet() const { return v_descriptionHasBeenSet; }
            void setDescription(const std::string &s_description ) {
                v_description = s_description;
                v_descriptionHasBeenSet = true;
            }
            const std::string &getGranularity()const { return  v_granularity; }
            bool GranularityHasBeenSet() const { return v_granularityHasBeenSet; }
            void setGranularity(const std::string &s_granularity ) {
                v_granularity = s_granularity;
                v_granularityHasBeenSet = true;
            }
            const std::string &getStrategy()const { return  v_strategy; }
            bool StrategyHasBeenSet() const { return v_strategyHasBeenSet; }
            void setStrategy(const std::string &s_strategy ) {
                v_strategy = s_strategy;
                v_strategyHasBeenSet = true;
            }
        private:
            std::string v_clientToken;
            bool v_clientTokenHasBeenSet;

            std::string v_deploymentSetName;
            bool v_deploymentSetNameHasBeenSet;

            std::string v_description;
            bool v_descriptionHasBeenSet;

            std::string v_granularity;
            bool v_granularityHasBeenSet;

            std::string v_strategy;
            bool v_strategyHasBeenSet;

        };
    }
}
#endif // !VOLCENGINE_ECS_CREATEDEPLOYMENTSETREQUEST_H