/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef VOLCENGINE_ECS_DESCRIBEDEPLOYMENTSETSREQUEST_H
#define VOLCENGINE_ECS_DESCRIBEDEPLOYMENTSETSREQUEST_H
#include <string>
#include <volcengine/core/RequestBuilder.h>

namespace volcengine{
    namespace ecs{
        class DescribeDeploymentSetsRequest {
        public:
            DescribeDeploymentSetsRequest();
            ~DescribeDeploymentSetsRequest() = default;

            RequestBuilder withRequestBuilder(RequestBuilder rb, const std::string &chain)const;

            const std::vector<std::string> &getDeploymentSetIds()const { return  v_deploymentSetIds; }
            bool DeploymentSetIdsHasBeenSet() const { return v_deploymentSetIdsHasBeenSet; }
            void setDeploymentSetIds(const std::vector<std::string> &s_deploymentSetIds ) {
                v_deploymentSetIds = s_deploymentSetIds;
                v_deploymentSetIdsHasBeenSet = true;
            }
            const std::string &getDeploymentSetName()const { return  v_deploymentSetName; }
            bool DeploymentSetNameHasBeenSet() const { return v_deploymentSetNameHasBeenSet; }
            void setDeploymentSetName(const std::string &s_deploymentSetName ) {
                v_deploymentSetName = s_deploymentSetName;
                v_deploymentSetNameHasBeenSet = true;
            }
            const std::string &getGranularity()const { return  v_granularity; }
            bool GranularityHasBeenSet() const { return v_granularityHasBeenSet; }
            void setGranularity(const std::string &s_granularity ) {
                v_granularity = s_granularity;
                v_granularityHasBeenSet = true;
            }
            int getMaxResults()const { return  v_maxResults; }
            bool MaxResultsHasBeenSet() const { return v_maxResultsHasBeenSet; }
            void setMaxResults(const int s_maxResults ) {
                v_maxResults = s_maxResults;
                v_maxResultsHasBeenSet = true;
            }
            const std::string &getNextToken()const { return  v_nextToken; }
            bool NextTokenHasBeenSet() const { return v_nextTokenHasBeenSet; }
            void setNextToken(const std::string &s_nextToken ) {
                v_nextToken = s_nextToken;
                v_nextTokenHasBeenSet = true;
            }
            const std::string &getStrategy()const { return  v_strategy; }
            bool StrategyHasBeenSet() const { return v_strategyHasBeenSet; }
            void setStrategy(const std::string &s_strategy ) {
                v_strategy = s_strategy;
                v_strategyHasBeenSet = true;
            }
        private:
            std::vector<std::string> v_deploymentSetIds;
            bool v_deploymentSetIdsHasBeenSet;

            std::string v_deploymentSetName;
            bool v_deploymentSetNameHasBeenSet;

            std::string v_granularity;
            bool v_granularityHasBeenSet;

            int v_maxResults;
            bool v_maxResultsHasBeenSet;

            std::string v_nextToken;
            bool v_nextTokenHasBeenSet;

            std::string v_strategy;
            bool v_strategyHasBeenSet;

        };
    }
}
#endif // !VOLCENGINE_ECS_DESCRIBEDEPLOYMENTSETSREQUEST_H