/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef VOLCENGINE_ECS_VOLUMEFORDESCRIBEINSTANCETYPESOUTPUT_H
#define VOLCENGINE_ECS_VOLUMEFORDESCRIBEINSTANCETYPESOUTPUT_H
#include <string>
#include <volcengine/core/RequestBuilder.h>
#include "volcengine/core/utils/json.hpp"
namespace volcengine{
    namespace ecs{
        class VolumeForDescribeInstanceTypesOutput {
        public:
            VolumeForDescribeInstanceTypesOutput() = default;
            ~VolumeForDescribeInstanceTypesOutput() = default;
            void fromJsonString(const std::string &input);
            const int getMaximumCount() const { return  v_maximumCount; }
            void setMaximumCount(const int s_maximumCount ) {
                v_maximumCount = s_maximumCount;
            }
            const std::vector<std::string> &getSupportedVolumeTypes() const { return  v_supportedVolumeTypes; }
            void setSupportedVolumeTypes(const std::vector<std::string> &s_supportedVolumeTypes ) {
                v_supportedVolumeTypes = s_supportedVolumeTypes;
            }
        private:
            int v_maximumCount{};
            std::vector<std::string> v_supportedVolumeTypes;
        };
    }
}
#endif // !VOLCENGINE_ECS_VOLUMEFORDESCRIBEINSTANCETYPESOUTPUT_H