/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#include "volcengine/clb/model/DescribeLoadBalancerAttributesResult.h"

using namespace volcengine;
using namespace volcengine::clb;
using namespace nlohmann;

void DescribeLoadBalancerAttributesResult::fromJsonString(const std::string &input) {
    auto j = json::parse(input);
    j = j.at("Result");
    if (j.contains("AccessLog")){
        json accessLogPres = j.at("AccessLog");
        auto next = std::make_shared<AccessLogForDescribeLoadBalancerAttributesOutput>();
        next->fromJsonString(to_string(accessLogPres));
        v_accessLog = next;
    }
    if (j.contains("AddressIpVersion")) j.at("AddressIpVersion").get_to(v_addressIpVersion);
    if (j.contains("BusinessStatus")) j.at("BusinessStatus").get_to(v_businessStatus);
    if (j.contains("CreateTime")) j.at("CreateTime").get_to(v_createTime);
    if (j.contains("DeletedTime")) j.at("DeletedTime").get_to(v_deletedTime);
    if (j.contains("Description")) j.at("Description").get_to(v_description);
    if (j.contains("Eip")){
        json eipPres = j.at("Eip");
        auto next = std::make_shared<EipForDescribeLoadBalancerAttributesOutput>();
        next->fromJsonString(to_string(eipPres));
        v_eip = next;
    }
    if (j.contains("EipAddress")) j.at("EipAddress").get_to(v_eipAddress);
    if (j.contains("EipID")) j.at("EipID").get_to(v_eipID);
    if (j.contains("Enabled")) j.at("Enabled").get_to(v_enabled);
    if (j.contains("EniAddress")) j.at("EniAddress").get_to(v_eniAddress);
    if (j.contains("EniID")) j.at("EniID").get_to(v_eniID);
    if (j.contains("EniIpv6Address")) j.at("EniIpv6Address").get_to(v_eniIpv6Address);
    if (j.contains("ExpiredTime")) j.at("ExpiredTime").get_to(v_expiredTime);
    if (j.contains("Ipv6AddressBandwidth")){
        json ipv6AddressBandwidthPres = j.at("Ipv6AddressBandwidth");
        auto next = std::make_shared<Ipv6AddressBandwidthForDescribeLoadBalancerAttributesOutput>();
        next->fromJsonString(to_string(ipv6AddressBandwidthPres));
        v_ipv6AddressBandwidth = next;
    }
    if (j.contains("Ipv6EipId")) j.at("Ipv6EipId").get_to(v_ipv6EipId);
    if (j.contains("Listeners")){
        json listenersPres = j.at("Listeners");
        for (auto & pre : listenersPres) {
           ListenerForDescribeLoadBalancerAttributesOutput next;
           next.fromJsonString(to_string(pre));
           v_listeners.emplace_back(next);
        }
    }
    if (j.contains("LoadBalancerBillingType")) j.at("LoadBalancerBillingType").get_to(v_loadBalancerBillingType);
    if (j.contains("LoadBalancerId")) j.at("LoadBalancerId").get_to(v_loadBalancerId);
    if (j.contains("LoadBalancerName")) j.at("LoadBalancerName").get_to(v_loadBalancerName);
    if (j.contains("LoadBalancerSpec")) j.at("LoadBalancerSpec").get_to(v_loadBalancerSpec);
    if (j.contains("LockReason")) j.at("LockReason").get_to(v_lockReason);
    if (j.contains("LogTopicId")) j.at("LogTopicId").get_to(v_logTopicId);
    if (j.contains("MasterZoneId")) j.at("MasterZoneId").get_to(v_masterZoneId);
    if (j.contains("ModificationProtectionReason")) j.at("ModificationProtectionReason").get_to(v_modificationProtectionReason);
    if (j.contains("ModificationProtectionStatus")) j.at("ModificationProtectionStatus").get_to(v_modificationProtectionStatus);
    if (j.contains("OverdueTime")) j.at("OverdueTime").get_to(v_overdueTime);
    if (j.contains("ProjectName")) j.at("ProjectName").get_to(v_projectName);
    if (j.contains("RequestId")) j.at("RequestId").get_to(v_requestId);
    if (j.contains("ServerGroups")){
        json serverGroupsPres = j.at("ServerGroups");
        for (auto & pre : serverGroupsPres) {
           ServerGroupForDescribeLoadBalancerAttributesOutput next;
           next.fromJsonString(to_string(pre));
           v_serverGroups.emplace_back(next);
        }
    }
    if (j.contains("ServiceManaged")) j.at("ServiceManaged").get_to(v_serviceManaged);
    if (j.contains("SlaveZoneId")) j.at("SlaveZoneId").get_to(v_slaveZoneId);
    if (j.contains("Status")) j.at("Status").get_to(v_status);
    if (j.contains("SubnetId")) j.at("SubnetId").get_to(v_subnetId);
    if (j.contains("Tags")){
        json tagsPres = j.at("Tags");
        for (auto & pre : tagsPres) {
           TagForDescribeLoadBalancerAttributesOutput next;
           next.fromJsonString(to_string(pre));
           v_tags.emplace_back(next);
        }
    }
    if (j.contains("Type")) j.at("Type").get_to(v_type);
    if (j.contains("UpdateTime")) j.at("UpdateTime").get_to(v_updateTime);
    if (j.contains("VpcId")) j.at("VpcId").get_to(v_vpcId);
}
