/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#include "volcengine/clb/model/ListenerForDescribeAclAttributesOutput.h"

using namespace volcengine;
using namespace volcengine::clb;
using namespace nlohmann;

void ListenerForDescribeAclAttributesOutput::fromJsonString(const std::string &input) {
    auto j = json::parse(input);
    if (j.contains("AclType")) j.at("AclType").get_to(v_aclType);
    if (j.contains("ListenerId")) j.at("ListenerId").get_to(v_listenerId);
    if (j.contains("ListenerName")) j.at("ListenerName").get_to(v_listenerName);
    if (j.contains("Port")) j.at("Port").get_to(v_port);
    if (j.contains("Protocol")) j.at("Protocol").get_to(v_protocol);
}
