/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef VOLCENGINE_VPC_CREATEVPCREQUEST_H
#define VOLCENGINE_VPC_CREATEVPCREQUEST_H
#include <string>
#include <volcengine/core/RequestBuilder.h>
#include "volcengine/vpc/model/TagForCreateVpcInput.h"

namespace volcengine{
    namespace vpc{
        class CreateVpcRequest {
        public:
            CreateVpcRequest();
            ~CreateVpcRequest() = default;

            RequestBuilder withRequestBuilder(RequestBuilder rb, const std::string &chain)const;

            const std::string &getCidrBlock()const { return  v_cidrBlock; }
            bool CidrBlockHasBeenSet() const { return v_cidrBlockHasBeenSet; }
            void setCidrBlock(const std::string &s_cidrBlock ) {
                v_cidrBlock = s_cidrBlock;
                v_cidrBlockHasBeenSet = true;
            }
            const std::string &getClientToken()const { return  v_clientToken; }
            bool ClientTokenHasBeenSet() const { return v_clientTokenHasBeenSet; }
            void setClientToken(const std::string &s_clientToken ) {
                v_clientToken = s_clientToken;
                v_clientTokenHasBeenSet = true;
            }
            const std::string &getDescription()const { return  v_description; }
            bool DescriptionHasBeenSet() const { return v_descriptionHasBeenSet; }
            void setDescription(const std::string &s_description ) {
                v_description = s_description;
                v_descriptionHasBeenSet = true;
            }
            const std::vector<std::string> &getDnsServers()const { return  v_dnsServers; }
            bool DnsServersHasBeenSet() const { return v_dnsServersHasBeenSet; }
            void setDnsServers(const std::vector<std::string> &s_dnsServers ) {
                v_dnsServers = s_dnsServers;
                v_dnsServersHasBeenSet = true;
            }
            const std::string &getProjectName()const { return  v_projectName; }
            bool ProjectNameHasBeenSet() const { return v_projectNameHasBeenSet; }
            void setProjectName(const std::string &s_projectName ) {
                v_projectName = s_projectName;
                v_projectNameHasBeenSet = true;
            }
            const std::vector<TagForCreateVpcInput> &getTags()const { return  v_tags; }
            bool TagsHasBeenSet() const { return v_tagsHasBeenSet; }
            void setTags(const std::vector<TagForCreateVpcInput> &s_tags ) {
                v_tags = s_tags;
                v_tagsHasBeenSet = true;
            }
            const std::string &getVpcName()const { return  v_vpcName; }
            bool VpcNameHasBeenSet() const { return v_vpcNameHasBeenSet; }
            void setVpcName(const std::string &s_vpcName ) {
                v_vpcName = s_vpcName;
                v_vpcNameHasBeenSet = true;
            }
        private:
            std::string v_cidrBlock;
            bool v_cidrBlockHasBeenSet;

            std::string v_clientToken;
            bool v_clientTokenHasBeenSet;

            std::string v_description;
            bool v_descriptionHasBeenSet;

            std::vector<std::string> v_dnsServers;
            bool v_dnsServersHasBeenSet;

            std::string v_projectName;
            bool v_projectNameHasBeenSet;

            std::vector<TagForCreateVpcInput> v_tags;
            bool v_tagsHasBeenSet;

            std::string v_vpcName;
            bool v_vpcNameHasBeenSet;

        };
    }
}
#endif // !VOLCENGINE_VPC_CREATEVPCREQUEST_H