/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef VOLCENGINE_VPC_DESCRIBEVPCSREQUEST_H
#define VOLCENGINE_VPC_DESCRIBEVPCSREQUEST_H
#include <string>
#include <volcengine/core/RequestBuilder.h>
#include "volcengine/vpc/model/TagFilterForDescribeVpcsInput.h"

namespace volcengine{
    namespace vpc{
        class DescribeVpcsRequest {
        public:
            DescribeVpcsRequest();
            ~DescribeVpcsRequest() = default;

            RequestBuilder withRequestBuilder(RequestBuilder rb, const std::string &chain)const;

            bool isIsDefault()const { return  v_isDefault; }
            bool IsDefaultHasBeenSet() const { return v_isDefaultHasBeenSet; }
            void setIsDefault(const bool s_isDefault ) {
                v_isDefault = s_isDefault;
                v_isDefaultHasBeenSet = true;
            }
            int getPageNumber()const { return  v_pageNumber; }
            bool PageNumberHasBeenSet() const { return v_pageNumberHasBeenSet; }
            void setPageNumber(const int s_pageNumber ) {
                v_pageNumber = s_pageNumber;
                v_pageNumberHasBeenSet = true;
            }
            int getPageSize()const { return  v_pageSize; }
            bool PageSizeHasBeenSet() const { return v_pageSizeHasBeenSet; }
            void setPageSize(const int s_pageSize ) {
                v_pageSize = s_pageSize;
                v_pageSizeHasBeenSet = true;
            }
            const std::string &getProjectName()const { return  v_projectName; }
            bool ProjectNameHasBeenSet() const { return v_projectNameHasBeenSet; }
            void setProjectName(const std::string &s_projectName ) {
                v_projectName = s_projectName;
                v_projectNameHasBeenSet = true;
            }
            const std::vector<TagFilterForDescribeVpcsInput> &getTagFilters()const { return  v_tagFilters; }
            bool TagFiltersHasBeenSet() const { return v_tagFiltersHasBeenSet; }
            void setTagFilters(const std::vector<TagFilterForDescribeVpcsInput> &s_tagFilters ) {
                v_tagFilters = s_tagFilters;
                v_tagFiltersHasBeenSet = true;
            }
            const std::vector<std::string> &getVpcIds()const { return  v_vpcIds; }
            bool VpcIdsHasBeenSet() const { return v_vpcIdsHasBeenSet; }
            void setVpcIds(const std::vector<std::string> &s_vpcIds ) {
                v_vpcIds = s_vpcIds;
                v_vpcIdsHasBeenSet = true;
            }
            const std::string &getVpcName()const { return  v_vpcName; }
            bool VpcNameHasBeenSet() const { return v_vpcNameHasBeenSet; }
            void setVpcName(const std::string &s_vpcName ) {
                v_vpcName = s_vpcName;
                v_vpcNameHasBeenSet = true;
            }
        private:
            bool v_isDefault;
            bool v_isDefaultHasBeenSet;

            int v_pageNumber;
            bool v_pageNumberHasBeenSet;

            int v_pageSize;
            bool v_pageSizeHasBeenSet;

            std::string v_projectName;
            bool v_projectNameHasBeenSet;

            std::vector<TagFilterForDescribeVpcsInput> v_tagFilters;
            bool v_tagFiltersHasBeenSet;

            std::vector<std::string> v_vpcIds;
            bool v_vpcIdsHasBeenSet;

            std::string v_vpcName;
            bool v_vpcNameHasBeenSet;

        };
    }
}
#endif // !VOLCENGINE_VPC_DESCRIBEVPCSREQUEST_H