/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#include <sstream>
#include <volcengine/core/RequestBuilder.h>
#include <volcengine/core/utils/StringUtils.h>
#include "volcengine/storageebs/model/CreateVolumeRequest.h"

using namespace volcengine;
using namespace volcengine::storageebs;
CreateVolumeRequest::CreateVolumeRequest() = default;

RequestBuilder CreateVolumeRequest::withRequestBuilder(RequestBuilder rb, const std::string &chain) const {
    rb.withQuery("Action","CreateVolume");
    rb.withQuery("Version","2020-04-01");

    if(v_clientTokenHasBeenSet){
        rb.withQuery(chain + "ClientToken", v_clientToken);

    }

    if(v_descriptionHasBeenSet){
        rb.withQuery(chain + "Description", v_description);

    }

    if(v_instanceIdHasBeenSet){
        rb.withQuery(chain + "InstanceId", v_instanceId);

    }

    if(v_kindHasBeenSet){
        rb.withQuery(chain + "Kind", v_kind);

    }

    if(v_projectNameHasBeenSet){
        rb.withQuery(chain + "ProjectName", v_projectName);

    }

    if(v_sizeHasBeenSet){
        rb.withQuery(chain + "Size", v_size);

    }

    if(v_tagsHasBeenSet){
      unsigned v_tagsCount = 1;
      for(auto& item : v_tags){
        std::stringstream ss;
        ss << chain << "Tags." << v_tagsCount;
        rb = item.withRequestBuilder(rb, ss.str()+".");
        v_tagsCount ++;
      }
    }

    if(v_volumeChargeTypeHasBeenSet){
        rb.withQuery(chain + "VolumeChargeType", v_volumeChargeType);

    }

    if(v_volumeNameHasBeenSet){
        rb.withQuery(chain + "VolumeName", v_volumeName);

    }

    if(v_volumeTypeHasBeenSet){
        rb.withQuery(chain + "VolumeType", v_volumeType);

    }

    if(v_zoneIdHasBeenSet){
        rb.withQuery(chain + "ZoneId", v_zoneId);

    }

    return rb;
}


