/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#include <sstream>
#include <volcengine/core/RequestBuilder.h>
#include <volcengine/core/utils/StringUtils.h>
#include "volcengine/vpn/model/DescribeVpnConnectionsRequest.h"

using namespace volcengine;
using namespace volcengine::vpn;
DescribeVpnConnectionsRequest::DescribeVpnConnectionsRequest(){
    v_pageNumber = 0;
    v_pageNumberHasBeenSet = false;
    v_pageSize = 0;
    v_pageSizeHasBeenSet = false;
}

RequestBuilder DescribeVpnConnectionsRequest::withRequestBuilder(RequestBuilder rb, const std::string &chain) const {
    rb.withQuery("Action","DescribeVpnConnections");
    rb.withQuery("Version","2020-04-01");

    if(v_attachStatusHasBeenSet){
        rb.withQuery(chain + "AttachStatus", v_attachStatus);

    }

    if(v_attachTypeHasBeenSet){
        rb.withQuery(chain + "AttachType", v_attachType);

    }

    if(v_customerGatewayIdHasBeenSet){
        rb.withQuery(chain + "CustomerGatewayId", v_customerGatewayId);

    }

    if(v_pageNumberHasBeenSet){
        rb.withQuery(chain + "PageNumber", std::to_string(v_pageNumber));

    }

    if(v_pageSizeHasBeenSet){
        rb.withQuery(chain + "PageSize", std::to_string(v_pageSize));

    }

    if(v_projectNameHasBeenSet){
        rb.withQuery(chain + "ProjectName", v_projectName);

    }

    if(v_transitRouterIdHasBeenSet){
        rb.withQuery(chain + "TransitRouterId", v_transitRouterId);

    }

    if(v_vpnConnectionIdsHasBeenSet){
      unsigned v_vpnConnectionIdsCount = 1;
      for(auto& item : v_vpnConnectionIds){
        std::stringstream ss;
        ss << chain << "VpnConnectionIds." << v_vpnConnectionIdsCount;
        rb.withQuery(ss.str(), item);
        v_vpnConnectionIdsCount ++;
      }
    }

    if(v_vpnConnectionNameHasBeenSet){
        rb.withQuery(chain + "VpnConnectionName", v_vpnConnectionName);

    }

    if(v_vpnGatewayIdHasBeenSet){
        rb.withQuery(chain + "VpnGatewayId", v_vpnGatewayId);

    }

    return rb;
}


