/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef VOLCENGINE_VPN_VPNGATEWAYFORDESCRIBEVPNGATEWAYSBILLINGOUTPUT_H
#define VOLCENGINE_VPN_VPNGATEWAYFORDESCRIBEVPNGATEWAYSBILLINGOUTPUT_H
#include <string>
#include <volcengine/core/RequestBuilder.h>
#include "volcengine/core/utils/json.hpp"
namespace volcengine{
    namespace vpn{
        class VpnGatewayForDescribeVpnGatewaysBillingOutput {
        public:
            VpnGatewayForDescribeVpnGatewaysBillingOutput() = default;
            ~VpnGatewayForDescribeVpnGatewaysBillingOutput() = default;
            void fromJsonString(const std::string &input);
            const int getBillingStatus() const { return  v_billingStatus; }
            void setBillingStatus(const int s_billingStatus ) {
                v_billingStatus = s_billingStatus;
            }
            const int getBillingType() const { return  v_billingType; }
            void setBillingType(const int s_billingType ) {
                v_billingType = s_billingType;
            }
            const std::string &getExpiredTime() const { return  v_expiredTime; }
            void setExpiredTime(const std::string &s_expiredTime ) {
                v_expiredTime = s_expiredTime;
            }
            const std::string &getReclaimTime() const { return  v_reclaimTime; }
            void setReclaimTime(const std::string &s_reclaimTime ) {
                v_reclaimTime = s_reclaimTime;
            }
            const int getRemainRenewTimes() const { return  v_remainRenewTimes; }
            void setRemainRenewTimes(const int s_remainRenewTimes ) {
                v_remainRenewTimes = s_remainRenewTimes;
            }
            const int getRenewType() const { return  v_renewType; }
            void setRenewType(const int s_renewType ) {
                v_renewType = s_renewType;
            }
            const std::string &getVpnGatewayId() const { return  v_vpnGatewayId; }
            void setVpnGatewayId(const std::string &s_vpnGatewayId ) {
                v_vpnGatewayId = s_vpnGatewayId;
            }
        private:
            int v_billingStatus{};
            int v_billingType{};
            std::string v_expiredTime;
            std::string v_reclaimTime;
            int v_remainRenewTimes{};
            int v_renewType{};
            std::string v_vpnGatewayId;
        };
    }
}
#endif // !VOLCENGINE_VPN_VPNGATEWAYFORDESCRIBEVPNGATEWAYSBILLINGOUTPUT_H