/*
* Code generated by Beijing Volcanoengine Technology.Do NOT EDIT.
* Copyright Beijing Volcanoengine Technology Ltd All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#include "volcengine/ecs/model/GpuDeviceForDescribeInstanceTypesOutput.h"

using namespace volcengine;
using namespace volcengine::ecs;
using namespace nlohmann;

void GpuDeviceForDescribeInstanceTypesOutput::fromJsonString(const std::string &input) {
    auto j = json::parse(input);
    if (j.contains("Count")) j.at("Count").get_to(v_count);
    if (j.contains("Memory")){
        json memoryPres = j.at("Memory");
        auto next = std::make_shared<MemoryForDescribeInstanceTypesOutput>();
        next->fromJsonString(to_string(memoryPres));
        v_memory = next;
    }
    if (j.contains("ProductName")) j.at("ProductName").get_to(v_productName);
}
